on: pull_request:
  types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: clang-format --dry-run --Werror *.cpp
  build:
    runs-on: ubuntu-latest
    needs: [format]
    steps:
    - uses: actions/checkout@v2 
    - run: make build # ?? 

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2 
      - run: doctest